#!/usr/bin/env ruby
require 'duffy'
require 'influxdb'

# CONFIG #
# InfluxDB Server:
influx_host = ENV['INFLUX_HOST'] || 'localhost'

# InfluxDB Database:
influx_db = ENV['INFLUX_DB'] || 'rb2db'

# Local Hostname
influx_localhost = ENV['INFLUX_LOCALHOST'] || `hostname`.strip

# Create Database for this host if it doesn't already exist
InfluxDB::Client.new(host: influx_host).create_database(influx_db)

# Connect to InfluxDB with database for this hostname selected
influxdb = InfluxDB::Client.new(influx_db, host: influx_host)

puts "Logging Started: #{influx_localhost} => #{influx_host}:#{influx_db}"
Process.daemon

while sleep 1
  data = [
    { series: 'cpu_percent',   tags: { host: influx_localhost }, values: { value: Duffy::System.cpu_percent } },
    { series: 'mem_total',     tags: { host: influx_localhost }, values: { value: Duffy::System.mem_total } },
    { series: 'mem_used',      tags: { host: influx_localhost }, values: { value: Duffy::System.mem_used } },
    { series: 'mem_available', tags: { host: influx_localhost }, values: { value: Duffy::System.mem_available } }
  ]
  influxdb.write_points(data)
end

